### ISSUE TITLE
Issues with sysmoISIM-SJA2 cards in Motorola Edge 20 Handset

### ISSUE THREAD

**Issue by wozzamac** [sysmocom/sysmo-usim-tool#4]
Hi,

I've recently purchased some sysmoISIM-SJA2 cards for our Private 5G network installation and they've worked well in our Samsung S22 and iPhone Pro 13 handsets.

However we're having issues using these cards in the Motorola Edge 20 handsets.

The Moto E20 handsets certainly can read the IMSI on the sysmoISIM-SJA2 cards (as we can see this in our Phone Debug menu) but they won't sync and PRACH/Connect to our 5G basestations.

We have another SIM card (from a different vendor) which does work in the Moto E20 handsets and we've tried matching the SIM file details/entries so the sysmoISIM-SJA2 cards match these other SIM cards, but still the Moto E20 handsets will not sync/connect.

Are there any known issues with the sysmoISIM-SJA2 cards on a Moto E20 handset? and if so is there anything you can recommend we try to get round this?

Many thanks,

Warren

**Comment by laf0rge** [comment]
Hi Warren,

a modern UICC/USIM/ISIM card contains thousands of paramters in hundreds of files. Any misconfiguration of any of them might render a card non-working in a given network.

I suppose you are familiar in general with the 5G related section of the  sysmoISIM-SJA2 user manual?

Are you sure EF.UAC_AIC (3GPP TS 31.102 section 4.4.11.7) contains configuration consistent with your network requirements/config?

How did you compare the working vs. non-working card? Did you do a full pySim-shell export for both the working and non-working card and look at the diff?  Would you mind sharing that diff (privately to support@sysmocom.de, as it may contain sensitive/confidential data)?

**Comment by wozzamac** [comment]
Thanks for the reply.

I used the pySim-shell tool to read both cards ADF.USIM EF file entries and then matched (programmed) the relevant file entries on the sysmoISIM-SJA2

I can certainly take a closer look at the EF.UAC_AIC files on both cards to see if I missed something there.

Yes I'm happy to share the pySim-shell export for each card, can you tell me what pySim-shell command options to enter so I can capture the relevant details for each SIM card?

Regards,

Warren

**Comment by laf0rge** [comment]
On Wed, Feb 14, 2024 at 01:42:01AM -0800, wozzamac wrote:
> Yes I'm happy to share the pySim-shell export for each card, can you tell me what pySim-shell command options to enter so I can capture the relevant details for each SIM card?

`export`, ideally after `verify_adm` if the ADM1 pin is known.

you can redirect the output like `export > /tmp/card1.export`

-- 
- Harald Welte ***@***.***>            https://www.sysmocom.de/
=======================================================================
* sysmocom - systems for mobile communications GmbH
* Alt-Moabit 93
* 10559 Berlin, Germany
* Sitz / Registered office: Berlin, HRB 134158 B
* Geschaeftsfuehrer / Managing Director: Harald Welte

**Comment by laf0rge** [comment]
Based on feedback received by private e-mail, there are many differences in the configuration of the working and the non-working card - including (But not limited) the fact that SUCI is enabled but no SUCI_Calc_Info is provided.  Closing this issue here.
